Repository Muhan-Company/bizcurator-ecommerce, pull requests merged in 2023-05, with the labels that each got.

#4 Header #3
  components/DownHeader.tsx
  components/Header.tsx
  components/Icons.tsx
  components/NavLink.tsx
  components/TopHeader.tsx
  pages/index.tsx
  styles/globals.css
Labels: Status : In Progress, Priority : Critical

#9 Cart item #5
  components/Icons.tsx
  components/cart/CartItem.tsx
  pages/cart/index.tsx
  public/img/image 68.png
Labels: Status : Completed, Priority : Medium, 🎨 Html&css, ✨ Feature

#12 Customer #6
  components/DownHeader.tsx
  components/customer/CustomerCenter.tsx
  components/customer/CustomerTabMenu.tsx
  components/customer/Kakao_consult.tsx
  components/customer/Notice.tsx
  components/customer/Question.tsx
  pages/customer/index.tsx
  tsconfig.json
Labels: Status : Completed, Priority : Medium, 🎨 Html&css, ✨ Feature

#8 Header #3
  components/Header.tsx
  components/LogInModal.tsx
  components/SearchModal.tsx
  components/TopHeader.tsx
  pages/search.tsx
Labels: Status : In Progress, Priority : Critical, 🎨 Html&css, ✨ Feature

#17 Cart item #5
  components/cart/CartItem.tsx
  components/cart/CartItemInfo.tsx
  components/cart/Counter.tsx
Labels: 🛠Refactoring

#18 Cart item list #10
  components/cart/CartItem.tsx
  components/cart/CartItemList.tsx
  components/cart/EmptyCart.tsx
  pages/cart/index.tsx
Labels: 🎨 Html&css, ✨ Feature

#16 Customer #6
  components/DownHeader.tsx
  components/admin/Home.tsx
  components/admin/SideBar.tsx
  components/customer/CustomerTabMenu.tsx
  components/customer/Kakao_consult.tsx
  components/customer/Notice.tsx
  components/customer/NoticeList.tsx
  components/customer/Question.tsx
  components/customer/QuestionList.tsx
  pages/admin/index.tsx
Labels: Priority : Medium, 🎨 Html&css, ✨ Feature

#22 Cart modals #20
  components/cart/CartItemInfo.tsx
  components/cart/Counter.tsx
  components/modal/CartAddModals.tsx
  components/modal/CartDeleteModals.tsx
  styles/globals.css
Labels: 🎨 Html&css, ✨ Feature, 🛠Refactoring

#25 Refactoring cart #21
  components/cart/CartItemInfo.tsx
  components/cart/CartItemList.tsx
Labels: 🎨 Html&css, 🛠Refactoring

#23 Main banner #15
  components/Header.tsx
  components/body/MainBanner.tsx
  components/header/DownHeader.tsx
  components/header/DropdownItem.tsx
  components/header/Header.tsx
  components/header/HeaderDropdown.tsx
  components/header/LogInModal.tsx
  components/header/NavLink.tsx
  components/header/SearchModal.tsx
  components/header/TopHeader.tsx
  package-lock.json
  package.json
  pages/index.tsx
  public/img/main 1.jpg
  public/img/main 2.jpg
  public/img/main 3.jpg
  styles/globals.css
Labels: Priority : Critical, 🎨 Html&css, ✨ Feature

#29 메인 페이지 - 전체 상품 카테고리
  components/body/ProductCategory.tsx
  components/body/ProductCategoryList.tsx
  pages/index.tsx
Labels: Status : In Progress, Priority : Critical, 🎨 Html&css, ✨ Feature

#28 My page main #27
  components/Icons.tsx
  components/mypage/MyPageMain.tsx
  pages/mypage/index.tsx
Labels: 🎨 Html&css, ✨ Feature

#33 Promo banner #31 - 홍보 배너 캐러셀 UI
  components/body/ProductCategory.tsx
  components/body/ProductCategoryList.tsx
  components/body/PromoBanner.tsx
  pages/index.tsx
  public/img/bannerImg1.png
  public/img/bannerImg2.png
  public/img/bannerImg3.png
  styles/globals.css
Labels: Status : In Progress, Priority : Critical, 🎨 Html&css, ✨ Feature

#30 Admin #14
  components/admin/AdminHeader.tsx
  components/admin/AdminSearch.tsx
  components/admin/Dashboard.tsx
  components/admin/DashboardContent.tsx
  components/admin/Home.tsx
  components/admin/OrderDelivery.tsx
  components/admin/SideBar.tsx
  components/admin/TabMenuBar.tsx
  components/customer/CustomerTabMenu.tsx
  pages/customer/index.tsx
Labels: Priority : Critical, 🎨 Html&css, ✨ Feature

#37 Product #34
  components/Icons.tsx
  components/body/MonthlyTrending.tsx
  components/body/Product.tsx
  components/body/PromoBanner.tsx
  components/body/Recommendation.tsx
  components/body/WeeklyTrending.tsx
  components/cart/Counter.tsx
  components/header/TopHeader.tsx
  components/modal/AddCompleteModal.tsx
  components/modal/AddToCartModal.tsx
  components/modal/CartAddModals.tsx
  components/modal/LogInModal.tsx
  components/modal/SearchModal.tsx
  pages/index.tsx
  public/img/tissue.png
  styles/globals.css
Labels: Status : In Progress, Type : Bug/Function, Priority : Critical, 🎨 Html&css, ✨ Feature, 🛠Refactoring

#38 메인 페이지 - Footer & NavBar
  atoms/modalAtoms.tsx
  components/Icons.tsx
  components/body/MonthProduct.tsx
  components/body/MonthlyTrending.tsx
  components/body/Recommendation.tsx
  components/body/RecommendationProduct.tsx
  components/body/WeekProduct.tsx
  components/body/WeeklyTrending.tsx
  components/footer/Footer.tsx
  components/footer/NavBar.tsx
  components/header/TopHeader.tsx
  components/modal/LogInModal.tsx
  components/modal/SearchModal.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/index.tsx
  styles/globals.css
Labels: Status : In Progress, Priority : Critical, 🎨 Html&css, ✨ Feature

#40 메인 페이지 - 제품구매 의뢰 배너 & 플로팅 버튼
  atoms/hoverAtoms.tsx
  components/Icons.tsx
  components/body/FloatingButton.tsx
  components/body/MainBanner.tsx
  components/body/MonthProduct.tsx
  components/body/MonthlyTrending.tsx
  components/body/Product.tsx
  components/body/ProductCategoryList.tsx
  components/body/PromoBanner.tsx
  components/body/Recommendation.tsx
  components/body/RequestBanner.tsx
  components/body/WeekProduct.tsx
  components/body/WeeklyTrending.tsx
  components/header/DownHeader.tsx
  components/header/Header.tsx
  components/header/TopHeader.tsx
  components/layout/Layout.tsx
  pages/api/hello.ts
  pages/index.tsx
  pages/mypage/index.tsx
  pages/user/cart/index.tsx
  pages/user/customer/index.tsx
Labels: Status : In Progress, Priority : Critical, 🎨 Html&css, ✨ Feature

#42 Orders #32
  components/orders/DateFilter.tsx
  components/orders/DeliveryStateFilter.tsx
  components/orders/EmptyOrderList.tsx
  components/orders/Order.tsx
  components/orders/OrderItem.tsx
  components/orders/OrderList.tsx
  pages/user/mypage/index.tsx
  pages/user/orders/index.tsx
Labels: 🎨 Html&css, ✨ Feature

#45 Admin #14
  components/customer/CustomerCenter.tsx
  components/customer/Kakao_consult.tsx
  components/customer/Notice.tsx
  components/customer/NoticeList.tsx
  components/modal/CustomWriteModal.tsx
Labels: Priority : Critical

#46 Orders detail #43
  components/orders/OrderItem.tsx
  components/orders/[paymentId]/DeliveryInfo.tsx
  components/orders/[paymentId]/OrderDetailLayout.tsx
  components/orders/[paymentId]/OrderInfo.tsx
  components/orders/[paymentId]/OrderItemInfo.tsx
  components/orders/[paymentId]/PaymentInfo.tsx
  pages/cart/index.tsx
  pages/customer/index.tsx
  pages/mypage/index.tsx
  pages/orders/[paymentId].tsx
  pages/orders/index.tsx
  styles/globals.css
  utils/getDelivreryStateToString.ts
Labels: 🎨 Html&css, ✨ Feature, 🛠Refactoring

#49 바로구매 페이지 #41
  atoms/seachBarAtom.tsx
  components/Icons.tsx
  components/body/ProductCategoryList.tsx
  components/footer/Footer.tsx
  components/header/ActiveLink.tsx
  components/header/DownHeader.tsx
  components/header/HeaderDropdown.tsx
  components/header/TopHeader.tsx
  components/home/FloatingButtons.tsx
  components/home/MainBanner.tsx
  components/home/MonthlyTrending.tsx
  components/home/Product.tsx
  components/home/ProductCategory.tsx
  components/home/ProductCategoryList.tsx
  components/home/PromoBanner.tsx
  components/home/Recommendation.tsx
  components/home/RequestBanner.tsx
  components/home/WeeklyTrending.tsx
  components/layout/Layout.tsx
  components/modal/SearchModal.tsx
  components/modal/SortModal.tsx
  components/products/CategoryFilter.tsx
  components/products/CategoryLink.tsx
  components/products/ProductList.tsx
  components/products/SearchBar.tsx
  components/products/Sort.tsx
  pages/cart/index.tsx
  pages/index.tsx
  pages/products/[category_id].tsx
  styles/globals.css
  tailwind.config.js
Labels: Status : Completed, Priority : Critical, 🎨 Html&css, ✨ Feature

#51 Customer #6
  components/Icons.tsx
  components/admin/Home.tsx
  components/admin/OrderDelivery.tsx
  components/admin/TabMenuBar.tsx
  components/customer/Kakao_consult.tsx
  components/customer/Notice.tsx
  components/customer/NoticeList.tsx
  components/modal/CustomWriteModal.tsx
  hooks/UseOnClickOutSide.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/admin/[tab].tsx
Labels: Priority : High, ✨ Feature, 🛠Refactoring

#52 바로 구매 - 제품 상세 페이지 #50
  atoms/modalAtoms.tsx
  components/Icons.tsx
  components/customer/NoticeList.tsx
  components/footer/NavBar.tsx
  components/header/DownHeader.tsx
  components/header/TopHeader.tsx
  components/home/Product.tsx
  components/modal/AddCompleteModal.tsx
  components/modals/AddCompleteModal.tsx
  components/modals/AddToCartModal.tsx
  components/modals/BuyCompleteModal.tsx
  components/modals/CartDeleteModals.tsx
  components/modals/CustomWriteModal.tsx
  components/modals/LogInModal.tsx
  components/modals/SearchModal.tsx
  components/modals/SortModal.tsx
  components/products/CategoryLink.tsx
  components/products/ProductCarousel.tsx
  components/products/ProductInfo.tsx
  components/products/Purchase.tsx
  components/products/Sort.tsx
  pages/products/[category_id].tsx
  pages/products/categories/[category_id].tsx
  pages/products/search.tsx
  styles/globals.css
Labels: Status : Completed, Priority : Critical, 🎨 Html&css, ✨ Feature

#53 Order cancel #47
  components/modal/SingleButtonModal.tsx
  components/orders/[paymentId]/OrderItemInfo.tsx
  components/orders/cancel/CancelInfo.tsx
  components/orders/cancel/CancelItemInfo.tsx
  components/orders/cancel/CancelOrderInfo.tsx
  components/orders/cancel/CancelReason.tsx
  components/orders/cancel/ReasonCategorySelector.tsx
  components/orders/cancel/RefundInfo.tsx
  hooks/useScrollLock.ts
  pages/orders/[paymentId].tsx
  pages/orders/cancel/[orderId].tsx
  styles/globals.css
Labels: 🎨 Html&css, ✨ Feature, 🛠Refactoring

#54 바로 구매 - 제품 상세 페이지 #50
  components/modals/AddCompleteModal.tsx
  components/modals/BuyCompleteModal.tsx
  components/products/Purchase.tsx
  package-lock.json
  package.json
  pages/_app.tsx
Labels: Status : Completed, Type : Enhancement, Priority : Critical, 🎨 Html&css, ✨ Feature, 🛠Refactoring

#60 Axios config #59
  apis/config/index.ts
  apis/config/interceptor.ts
Labels: ✨ Feature

#65 구매/제작 의뢰 페이지 - #55
  atoms/hoverAtom.tsx
  components/Icons.tsx
  components/Toasters/Notification.tsx
  components/header/ActiveLink.tsx
  components/header/DownHeader.tsx
  components/header/TopHeader.tsx
  components/modals/AddCompleteModal.tsx
  components/modals/AddToCartModal.tsx
  components/modals/BuyCompleteModal.tsx
  components/modals/LogInModal.tsx
  components/modals/SearchModal.tsx
  components/modals/SortModal.tsx
  components/request/ActiveLink2.tsx
  components/request/DatePicker.tsx
  components/request/Description.tsx
  components/request/FormTitle.tsx
  components/request/ManufactureForm.tsx
  components/request/MyInfo.tsx
  components/request/Numbers/Five.tsx
  components/request/Numbers/Four.tsx
  components/request/Numbers/One.tsx
  components/request/Numbers/Six.tsx
  components/request/Numbers/Three.tsx
  components/request/Numbers/Two.tsx
  components/request/PurchaseForm.tsx
  package-lock.json
  package.json
  pages/_app.tsx
  pages/request/manufacture/index.tsx
  pages/request/purchase/index.tsx
  styles/globals.css
  tailwind.config.js
Labels: Status : Completed, Priority : High, 🎨 Html&css, ✨ Feature

#63 Cancel refund list #61
  apis/cancel&refund.ts
  atoms/cancel&refundAtoms.ts
  atoms/selectedDateFilterAtom.ts
  components/cancel-refund/CancelRefundOrderItem.tsx
  components/cancel-refund/CancelRefundOrderItemContainer.tsx
  components/cancel-refund/CancelRefundOrderList.tsx
  components/layout/CancelReFundPageLayout.tsx
  components/orders/DateFilter.tsx
  components/orders/OrderItem.tsx
  pages/cancel-refund/index.tsx
Labels: 🎨 Html&css, ✨ Feature

#68 Cancel refund detail #67
  apis/cancel&refund.ts
  components/cancel-refund/CancelRefundDetailInfoContainer.tsx
  components/cancel-refund/CancelRefundDetailOrderInfo.tsx
  components/cancel-refund/RefundInfo.tsx
  pages/cancel-refund/[...details].tsx
Labels: 🎨 Html&css, ✨ Feature, 🛠Refactoring

#70 My requests #69
  components/my-requests/EditRequestContainer.tsx
  components/my-requests/MyRequestsListContainer.tsx
  components/my-requests/MyRequestsListTable.tsx
  components/my-requests/RequestDetailContainer.tsx
  components/my-requests/RequestDetailHeader.tsx
  components/my-requests/RequestDetailInfo.tsx
  components/my-requests/RequestsState.tsx
  pages/my-requests/edit/[...reqType].tsx
  pages/my-requests/index.tsx
  pages/my-requests/manufacture/[id].tsx
  pages/my-requests/purchase/[id].tsx
Labels: 🎨 Html&css, ✨ Feature

#73 인기 상품 조회, 상품 상세정보 조회, 장바구니 담기 API - #66
  apis/cartApis.ts
  apis/config/index.ts
  apis/productApis.ts
  apis/trendingApi.ts
  atoms/hoverAtom.ts
  atoms/modalAtoms.ts
  atoms/seachBarAtom.ts
  components/Toasters/Notification.tsx
  components/cart/Counter.tsx
  components/footer/Footer.tsx
  components/home/MonthlyTrending.tsx
  components/home/Product.tsx
  components/home/WeeklyTrending.tsx
  components/modals/AddToCartModal.tsx
  components/products/Loader.tsx
  components/products/ProductCarousel.tsx
  components/products/ProductInfo.tsx
  components/products/Purchase.tsx
  components/request/MyInfo.tsx
  components/request/Numbers/One.tsx
  hooks/useAddCompleteModal.ts
  hooks/useCustomMutation.ts
  hooks/useInvalidation.ts
  hooks/useToast.ts
  next.config.js
  package-lock.json
  pages/index.tsx
  pages/products/[category_id].tsx
  styles/globals.css
Labels: Status : Completed, Priority : Critical, Type: Bugfix/UI, 🎨 Html&css, ✨ Feature

#77 Admin #14
  .env
  apis/adminEntrance.ts
  apis/adminMemberManage.ts
  apis/adminOrderCancel.ts
  apis/adminOrderDelivery.ts
  apis/adminProductModify.ts
  apis/adminPurchase.ts
  apis/adminSales.ts
  apis/adminVendorList.ts
  apis/deliveryApi.ts
  atoms/adminAtoms.tsx
  atoms/adminCancelAtoms.tsx
  atoms/notice.ts
  components/admin/AdminSearch.tsx
  components/admin/Dashboard.tsx
  components/admin/DashboardContent.tsx
  components/admin/EntranceRequest.tsx
  components/admin/FileUpload.tsx
  components/admin/LoginForm.tsx
  components/admin/MemberManage.tsx
  components/admin/OrderCancel.tsx
  components/admin/OrderDelivery.tsx
  components/admin/OrderDummy.ts
  components/admin/ProductModify.tsx
  components/admin/ProductRegister.tsx
  components/admin/PurchaseRequest.tsx
  components/admin/SalesRequest.tsx
  components/admin/SidebarItem.tsx
  components/admin/TableComponent.tsx
  components/admin/VendorList.tsx
  components/customer/Notice.tsx
  components/customer/NoticeList.tsx
  components/modals/CustomModal.tsx
  components/modals/CustomWriteModal.tsx
  package-lock.json
  package.json
  pages/admin/Dashboard.tsx
  pages/admin/EntranceRequest.tsx
  pages/admin/MemberManage.tsx
  pages/admin/OrderCancel.tsx
  pages/admin/OrderDelivery.tsx
  pages/admin/OrderRefund.tsx
  pages/admin/ProductModify.tsx
  pages/admin/ProductRegister.tsx
  pages/admin/PurchaseRequest.tsx
  pages/admin/SalesRequest.tsx
  pages/admin/VendorList.tsx
  pages/admin/index.tsx
  pages/admin/paginated.tsx
  pages/api/[page].ts
  pages/api/todo.ts
  utils/type/adminRegister.ts
  utils/types/responseType.ts
Labels: Type : Bug/Function, Type : Enhancement, Priority : Critical, Type: Bugfix/UI, 🎨 Html&css, ✨ Feature

#78 상품 검색/카테고리별 상품 조회 #76
  apis/productApis.ts
  apis/searchApi.ts
  atoms/sortByAtom.ts
  components/header/ActiveLink.tsx
  components/header/DownHeader.tsx
  components/header/TopHeader.tsx
  components/home/MonthlyTrending.tsx
  components/home/Product.tsx
  components/home/WeeklyTrending.tsx
  components/modals/SearchModal.tsx
  components/modals/SingleButtonModal.tsx
  components/modals/SortModal.tsx
  components/orders/cancel&refund/CancelInfo.tsx
  components/orders/cancel&refund/RefundRequestInfo.tsx
  components/products/CategoryFilter.tsx
  components/products/CategoryLink.tsx
  components/products/Loader.tsx
  components/products/ProductImage.tsx
  components/products/ProductInfo.tsx
  components/products/ProductList.tsx
  components/products/SearchBar.tsx
  components/products/Sort.tsx
  hooks/UseOnClickOutSide.ts
  hooks/useCategories.ts
  hooks/useProductInfo.ts
  hooks/useSearch.ts
  next.config.js
  pages/_app.tsx
  pages/index.tsx
  pages/products/[category_id].tsx
  pages/products/categories/[category_id].tsx
  pages/products/results/index.tsx
  pages/products/search.tsx
Labels: Status : Completed, Priority : High, ✨ Feature

#79 Users #71
  apis/config/index.ts
  apis/config/interceptor.ts
  apis/users.ts
  components/ScrollToTop.tsx
  components/SearchAddressForm.tsx
  components/modals/LogInModal.tsx
  components/users/LabeledInput.tsx
  components/users/LoginForm.tsx
  components/users/SectionMarginLayout.tsx
  components/users/SignupForm.tsx
  components/users/formSchma.ts
  components/users/types.ts
  package.json
  pages/_app.tsx
  pages/signup/index.tsx
  styles/globals.css
  utils/constants.ts
Labels: 🎨 Html&css, ✨ Feature

#72 Customer #6
  apis/config/index.ts
  apis/config/questionPostsApi.ts
  atoms/modalAtoms.ts
  atoms/noticeAtom.ts
  atoms/questionAtom.ts
  atoms/scrollAtom.ts
  components/admin/OrderDummy.ts
  components/customer/Notice.tsx
  components/customer/Question.tsx
  components/customer/QuestionList.tsx
  components/modals/ConfirmModal.tsx
  utils/noticeApi.ts
Labels: Priority : Critical, Type: Bugfix/UI, ✨ Feature, 🛠Refactoring

#81 Customer #6
  .env
  .vscode/settings.json
  apis/config/index.ts
  components/admin/AdminProductRegister.tsx
  components/admin/ProductRegister.tsx
  components/customer/Notice.tsx
  components/customer/NoticeList.tsx
  components/customer/Question.tsx
  components/customer/QuestionList.tsx
  components/modals/CustomWriteModal.tsx
  next.config.js
  pages/_app.tsx
  pages/admin/ProductRegister.tsx
  pages/admin/VendorList.tsx
  utils/types/responseType.ts
Labels: Priority : High, ✨ Feature

#85 Cart api #26
  apis/cartApis.ts
  components/cart/CartItem.tsx
  components/cart/CartItemInfo.tsx
  components/cart/CartItemList.tsx
  components/cart/CartPaymentAmountInfo.tsx
Labels: ✨ Feature, 🛠Refactoring

#101 구매/제작/입점 의뢰 - #80
  apis/productApis.ts
  apis/requestApis.ts
  apis/searchApi.ts
  apis/trendingApi.ts
  atoms/reqSuccessAtom.ts
  components/footer/NavBar.tsx
  components/home/Product.tsx
  components/modals/AddToCartModal.tsx
  components/products/Loader.tsx
  components/request/CompanyInfo.tsx
  components/request/CompanyInput.tsx
  components/request/CompanyValue.tsx
  components/request/Description.tsx
  components/request/ManufactureForm.tsx
  components/request/MyInfo.tsx
  components/request/Numbers/Five.tsx
  components/request/Numbers/Four.tsx
  components/request/Numbers/NumOne.tsx
  components/request/Numbers/NumThree.tsx
  components/request/Numbers/NumTwo.tsx
  components/request/Numbers/One.tsx
  components/request/Numbers/Six.tsx
  components/request/Numbers/Two.tsx
  components/request/PartnerForm.tsx
  components/request/PurchaseForm.tsx
  hooks/useCategories.ts
  hooks/useProductInfo.ts
  hooks/useSearch.ts
  pages/my-requests/index.tsx
  pages/partners/index.tsx
  pages/products/[category_id].tsx
  pages/products/categories/[category_id].tsx
  pages/products/results/index.tsx
  pages/request/manufacture/index.tsx
  pages/request/purchase/index.tsx
Labels: Status : Completed, Priority : High, ✨ Feature
